// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using OS.DAL.PgSql;
using System;

namespace OS.DAL.PgSql.Migrator.Migrations
{
    [DbContext(typeof(DeviceDbContext))]
    [Migration("20171210234443_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("OS.DAL.PgSql.Model.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AddressId");

                    b.Property<double>("Lat");

                    b.Property<double>("Lon");

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.Property<long?>("VendorId");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("VendorId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("OS.DAL.PgSql.Model.PostalAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("CountryCode");

                    b.Property<string>("State");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("PostalAddresses");
                });

            modelBuilder.Entity("OS.DAL.PgSql.Model.Vendor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("OS.DAL.PgSql.Model.VendorApiKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<int>("Limit");

                    b.Property<long?>("VendorId");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorApiKeys");
                });

            modelBuilder.Entity("OS.DAL.PgSql.Model.Device", b =>
                {
                    b.HasOne("OS.DAL.PgSql.Model.PostalAddress", "Address")
                        .WithOne("Device")
                        .HasForeignKey("OS.DAL.PgSql.Model.Device", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OS.DAL.PgSql.Model.Vendor", "Vendor")
                        .WithMany("Devices")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OS.DAL.PgSql.Model.VendorApiKey", b =>
                {
                    b.HasOne("OS.DAL.PgSql.Model.Vendor", "Vendor")
                        .WithMany("Keys")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
