apiVersion: v1
kind: Secret
metadata:
  name: os-smog-api.secrets
  namespace: #{k8s.namespace}#
data:
  os-smog-api.measurementsDatabase: #{os-smog-api.measurementsDb}#
  os-smog-api.devicesDatabase: #{os-smog-api.devicesDb}#
  os-smog-api.azureStorage: #{os-smog-api.azureStorage}#
  os-smog-api.azureWebJobStorage: #{os-smog-api.azureWebJobStorage}#